// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
using Pharmacies.Tests;

namespace Pharmacies.Tests
{
    public class SearchingPharmaciesTest : SeleniumBase
    {

        [Fact]
        public void SearchingTest()
        {
            driver.Navigate().GoToUrl("https://localhost:44348/");
            driver.Manage().Window.Size = new System.Drawing.Size(945, 1030);
            Thread.Sleep(2000);
            driver.FindElement(By.Id("searchBox")).Click();
            driver.FindElement(By.Id("searchBox")).SendKeys("Cechowa 1");
            {
                var element = driver.FindElement(By.CssSelector(".row:nth-child(2) > .col"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
        }
    }

}
