// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;

namespace Pharmacies.Tests
{
    public class SeleniumLoginTest : SeleniumBase
    {
       
        [Fact]
        public void LoginTest()
        {
            driver.Navigate().GoToUrl("https://localhost:44348/");
            driver.Manage().Window.Size = new System.Drawing.Size(1936, 1066);
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("k.abramczyk98@wp.pl");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Password123!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("logout")).Click();
            {
                var element = driver.FindElement(By.Id("login"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                Actions builder = new Actions(driver);

            }
        }

    }

}
